# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
class BuildNumberFactory
  class << self
    def make
      `git rev-list HEAD --count`
    end
  end
end
before_all do
  setup_semaphore
end
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    sync_code_signing(type: "appstore", readonly: is_ci)
    increment_version_number_in_plist
    build_app(workspace: "ios/jokesApp.xcworkspace", scheme: "jokesApp", clean: true,silent: true,xcargs: "ONLY_ACTIVE_ARCH=YES",)
    upload_to_testflight
  end
end
