apiVersion: v1alpha
kind: Project
metadata:
  name: appjokes
spec:
  repository:
    url: 'git@github.com/santisolis-u/jokesapp.git'
    run: true
    run_on:
      - branches
      - tags
    pipeline_file: '.semaphore/semaphore.yml'
    status:
      pipeline_files:
        - path: '.semaphore/semaphore.yml'
          level: 'pipeline'
